# Generated by Django 5.1 on 2025-03-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=255)),
                ('subtypes', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('full_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.FloatField()),
                ('reviews_link', models.TextField()),
                ('reviews_tags', models.TextField()),
                ('photo', models.TextField()),
                ('street_view', models.TextField()),
            ],
        ),
    ]
